INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (1, 'A a', 'ah / eh', 'Sounds like "a" in "father" (long) or "cat" (short).');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (1, 'B b', 'b', 'Like a soft English "b".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (1, 'C c', 's / k', 'Sounds like "s" or "k" depending on the following vowel.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (1, 'D d', 'd / th', 'Hard "d" at start; soft "th" (like "this") in middle/end.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (1, 'E e', 'eh', 'Sounds like "e" in "bed" or a neutral "uh" sound.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (1, 'F f', 'f', 'Like the English "f".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (1, 'G g', 'g / y', 'Hard "g" at start; often a "y" sound or silent in middle/end.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (1, 'H h', 'h', 'Like English "h". Silent before "v" and "j".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (1, 'I i', 'ee / i', 'Like "ee" in "see" or "i" in "bit".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (1, 'J j', 'y', 'Always sounds like the "y" in "yes".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (1, 'K k', 'k', 'Like the English "k".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (1, 'L l', 'l', 'Like the English "l".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (1, 'M m', 'm', 'Like the English "m".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (1, 'N n', 'n', 'Like the English "n".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (1, 'O o', 'oh', 'Like the "o" in "go" or "hot".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (1, 'P p', 'p', 'Like the English "p".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (1, 'Q q', 'k', 'Sounds like "k".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (1, 'R r', 'r', 'A deep, guttural "r" from the back of the throat.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (1, 'S s', 's', 'Like the "s" in "sun".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (1, 'T t', 't', 'Like the English "t".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (1, 'U u', 'oo', 'Like the "oo" in "boot".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (1, 'V v', 'v', 'Like the English "v".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (1, 'W w', 'v', 'Like the English "v".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (1, 'X x', 'ks', 'Like "ks".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (1, 'Y y', 'ue', 'Say "ee" with rounded lips (sounds like "yoo").');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (1, 'Z z', 's', 'Sounds like "s".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (1, 'AE ae', 'eh', 'The letter Æ; sounds like "e" in "bed".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (1, 'OE oe', 'eu', 'The letter Ø; like "i" in "bird" or "eu" in French.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (1, 'AA aa', 'aw', 'The letter Å; sounds like the "o" in "lord".');