INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (2, 'A a', 'a', 'short a as in act');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (2, 'Õ õ', 'e', 'sounds like "oo"');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (2, 'Ä ä', 'ä', 'a cross between a and the long e');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (2, 'Ö ö', 'ou', 'a cross between u and i');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (2, 'Š š', 'sh', 'sounds like sh in shoe');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (2, 'Ž ž', 'j', 'j as in jealous');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (2, 'A a', 'a', 'ah as in father');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (2, 'E e', 'e', 'short e as in bed');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (2, 'I i', 'ee', 'between i and e as in mean');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (2, 'O o', 'o', 'long o as in boat');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (2, 'U u', 'u', 'u in put and the oo in boot');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (2, 'B b', 'p', 'like a soft p like lip, but a little softer');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (2, 'C c', 'c', 'only occurs in foreign names');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (2, 'D d', 't', 'like a weak t like mat');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (2, 'F f', 'f', 'like the f in fat');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (2, 'G g', 'k', 'like a weak k like back, but softer');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (2, 'H h', 'h', 'usually sounded, but sometimes silent');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (2, 'J j', 'y', 'like a y yet');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (2, 'K k', 'k', 'same as king');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (2, 'L l', 'l', 'same as like');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (2, 'M m', 'm', 'same as million');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (2, 'N n', 'n', 'same as night');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (2, 'P p', 'p', 'same as please');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (2, 'Q q', 'q', 'only occurs in foreign names');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (2, 'R r', 'r', 'same as ring');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (2, 'S s', 's', 'same as sing');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (2, 'T t', 't', 'same as train');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (2, 'V v', 'v', 'same as have');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (2, 'W w', 'w', 'only in foreign names');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (2, 'X x', 'x', 'only in foreign names');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (2, 'Y y', 'y', 'only in foreign names');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (2, 'Z z', 'z', 'same as zebra');