INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (5, 'A a', 'ah', 'Like "a" in "father".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (5, 'B b', 'b / p', 'Like "b" in "book"; sounds like "p" at end of words.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (5, 'C c', 'ts / k', 'Like "ts" or "k".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (5, 'D d', 'd / t', 'Like "d" in "dog"; sounds like "t" at end of words.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (5, 'E e', 'ay / eh', 'Like "ay" in "say" or "e" in "bed".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (5, 'F f', 'f', 'Like English "f".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (5, 'G g', 'g / k', 'Hard "g"; sounds like "k" at end of words.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (5, 'H h', 'h', 'Standard "h"; silent when it lengthens a vowel.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (5, 'I i', 'ee / i', 'Like "ee" in "see" or "i" in "bit".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (5, 'J j', 'y', 'Always sounds like English "y" in "yes".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (5, 'K k', 'k', 'Like English "k".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (5, 'L l', 'l', 'Like English "l".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (5, 'M m', 'm', 'Like English "m".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (5, 'N n', 'n', 'Like English "n".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (5, 'O o', 'oh', 'Like "o" in "go" or "hot".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (5, 'P p', 'p', 'Like English "p".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (5, 'Q q', 'kv', 'Sounds like "kv".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (5, 'R r', 'r', 'Guttural "r" from the back of the throat.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (5, 'S s', 'z / s', 'Like "z" at start of words; like "s" at end.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (5, 'T t', 't', 'Like English "t".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (5, 'U u', 'oo', 'Like "oo" in "boot".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (5, 'V v', 'f', 'Usually sounds like English "f".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (5, 'W w', 'v', 'Always sounds like English "v".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (5, 'X x', 'ks', 'Like English "ks".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (5, 'Y y', 'ue', 'Sounds like German "ue" (rounded "ee").');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (5, 'Z z', 'ts', 'Always sounds like "ts" in "cats".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (5, 'Ä ä', 'eh', 'The umlauted A; sounds like "e" in "bed".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (5, 'Ö ö', 'eu', 'The umlauted O; like "i" in "bird" with rounded lips.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (5, 'Ü ü', 'ue', 'The umlauted U; like "ee" in "see" with rounded lips.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (5, 'ß', 's', 'The "Eszett"; sounds like a sharp "s".');