INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (3, 'A a', 'ah', 'Short like "u" in "cut"; long like "a" in "father".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (3, 'Ą ą', 'ah', 'Always a long "ah" sound.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (3, 'B b', 'b', 'Like English "b".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (3, 'C c', 'ts', 'Always like "ts" in "cats".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (3, 'Č č', 'ch', 'Like "ch" in "church".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (3, 'D d', 'd', 'Like English "d".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (3, 'E e', 'eh', 'Short like "e" in "get"; long like "a" in "man".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (3, 'Ę ę', 'eh', 'Always a long, open "eh" sound.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (3, 'Ė ė', 'ay', 'Long closed "e" like "ay" in "say".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (3, 'F f', 'f', 'Like English "f".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (3, 'G g', 'g', 'Hard "g" as in "go".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (3, 'H h', 'h', 'Voiced "h", slightly breathy.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (3, 'I i', 'ih', 'Short "i" as in "bit".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (3, 'Į į', 'ee', 'Always a long "ee" sound.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (3, 'Y y', 'ee', 'Always a long "ee" sound.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (3, 'J j', 'y', 'Like the "y" in "yes".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (3, 'K k', 'k', 'Like English "k" (unaspirated).');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (3, 'L l', 'l', 'Like "l" in "lamp".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (3, 'M m', 'm', 'Like English "m".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (3, 'N n', 'n', 'Like English "n".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (3, 'O o', 'oh', 'Usually long, like "o" in "more".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (3, 'P p', 'p', 'Like English "p" (unaspirated).');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (3, 'R r', 'r', 'A rolled or trilled "r".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (3, 'S s', 's', 'Sharp "s" as in "sun".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (3, 'Š š', 'sh', 'Like "sh" in "ship".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (3, 'T t', 't', 'Like English "t" (unaspirated).');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (3, 'U u', 'u', 'Short "u" as in "put".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (3, 'Ų ų', 'oo', 'Always a long "oo" sound.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (3, 'Ū ū', 'oo', 'Always a long "oo" sound.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (3, 'V v', 'v', 'Like English "v".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (3, 'Z z', 'z', 'Like English "z".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (3, 'Ž ž', 'zh', 'Like "s" in "measure".');