INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (6, 'А а', 'ah', 'Like "a" in "father".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (6, 'Б б', 'b', 'Like "b" in "bad".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (6, 'В в', 'v', 'Like "v" in "vine".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (6, 'Г г', 'g', 'Always hard like "g" in "go".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (6, 'Д д', 'd', 'Like "d" in "dog".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (6, 'Е е', 'ye', 'Like "ye" in "yes".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (6, 'Ё ё', 'yo', 'Like "yo" in "yonder". Always stressed.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (6, 'Ж ж', 'zh', 'Like "s" in "measure". Always hard.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (6, 'З з', 'z', 'Like "z" in "zoo".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (6, 'И и', 'ee', 'Like "ee" in "see". Softens the preceding consonant.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (6, 'Й й', 'y', 'Short "i". Like "y" in "boy".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (6, 'К к', 'k', 'Like "k" in "kitten" (unaspirated).');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (6, 'Л л', 'l', 'Like "l" in "lamp".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (6, 'М м', 'm', 'Like "m" in "map".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (6, 'Н н', 'n', 'Like "n" in "no".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (6, 'О о', 'o / ah', 'Like "o" in "bore" (stressed) or "a" in "father" (unstressed).');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (6, 'П п', 'p', 'Like "p" in "pot" (unaspirated).');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (6, 'Р р', 'r', 'A rolled "r" like in Spanish or Italian.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (6, 'С с', 's', 'Always sharp like "s" in "set".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (6, 'Т т', 't', 'Like "t" in "top" (unaspirated).');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (6, 'У у', 'oo', 'Like "oo" in "boot".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (6, 'Ф ф', 'f', 'Like "f" in "face".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (6, 'Х х', 'kh', 'Like "ch" in Scottish "loch" or Spanish "J".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (6, 'Ц ц', 'ts', 'Like "ts" in "cats". Always hard.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (6, 'Ч ч', 'ch', 'Like "ch" in "chip". Always soft.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (6, 'Ш ш', 'sh', 'Like "sh" in "shut" (retroflex/hard).');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (6, 'Щ щ', 'shch', 'Like "sh" in "sheep" but longer and softer.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (6, 'Ъ ъ', '-', 'Hard sign. No sound; indicates a pause between consonant and vowel.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (6, 'Ы ы', 'i', 'Like "i" in "ill" or "it", but pronounced further back in the throat.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (6, 'Ь ь', '-', 'Soft sign. No sound; palatalizes (softens) the preceding consonant.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (6, 'Э э', 'e', 'Like "e" in "met".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (6, 'Ю ю', 'yu', 'Like "u" in "universe".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (6, 'Я я', 'ya', 'Like "ya" in "yard".');