INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (4, 'A a', 'ah', 'Pure vowel, like "a" in "father".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (4, 'B b', 'b', 'Standard "b", but softer between vowels.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (4, 'C c', 'k / s', 'Hard "k" before a, o, u; soft "s" (or "th") before e, i.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (4, 'D d', 'd / th', 'Hard "d" at start; soft "th" (like "this") between vowels.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (4, 'E e', 'eh', 'Short vowel, like "e" in "met".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (4, 'F f', 'f', 'Like English "f".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (4, 'G g', 'g / h', 'Hard "g" (goat) or raspy "h" (before e, i).');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (4, 'H h', '-', 'Always silent.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (4, 'I i', 'ee', 'Like "ee" in "see".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (4, 'J j', 'h', 'A raspy, strong English "h" sound.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (4, 'K k', 'k', 'Like English "k".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (4, 'L l', 'l', 'Like English "l".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (4, 'M m', 'm', 'Like English "m".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (4, 'N n', 'n', 'Like English "n".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (4, 'Ñ ñ', 'ny', 'Like "ny" in "canyon".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (4, 'O o', 'oh', 'Like "o" in "boy" but without the "y" glide.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (4, 'P p', 'p', 'Like English "p" (unaspirated).');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (4, 'Q q', 'k', 'Always followed by silent "u". Like "k".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (4, 'R r', 'r', 'A single tongue tap, like "tt" in "butter".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (4, 'S s', 's', 'Always a sharp "s".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (4, 'T t', 't', 'Like English "t" but tongue touches teeth.');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (4, 'U u', 'oo', 'Like "oo" in "food".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (4, 'V v', 'b', 'Exactly the same sound as "b".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (4, 'W w', 'w', 'Like English "w".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (4, 'X x', 'ks', 'Like "ks" or "s".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (4, 'Y y', 'y', 'Like "y" in "yes".');
INSERT INTO alphabet(lang_id, letter_symbol, pronunciation, explanation) VALUES (4, 'Z z', 's / th', 'Like "s" (Americas) or "th" (Spain).');